"""Stable device capabilities and runtime API.

Concrete products live below domain-specific provider packages. Application
and execution code import only the symbols exported here.
"""

from .runtime.arm_models import (
    ArmId,
    ArmState,
    ArmTelemetry,
    CartesianPose,
    GripperTelemetry,
    JointVector,
    MotionMode,
    MotionOptions,
    RobotOperationError,
    TrajectorySaveResult,
)
from .runtime.camera_models import DepthCameraFrame
from .runtime.sensor_models import BalanceReading
from .runtime.contracts import (
    ArmMotion,
    ArmStateReader,
    ArmTelemetryReader,
    BodyAxis,
    BalanceReader,
    CameraSource,
    DepthCameraSource,
    DigitalOutputs,
    ExpressionDisplay,
    GripperControl,
    GrippingRobotSystem,
    MobileBase,
    NeckMotion,
    Pipette,
    PowderDispenser,
    RobotSystem,
    RobotTeleoperation,
    SelectableCameraSource,
    StoppableDevice,
    ToolChanger,
    ToolRackControl,
    TrajectoryControl,
)
from .runtime.models import (
    DeviceCapability,
    DeviceContractError,
    DeviceErrorCategory,
    DeviceInitializationError,
    DeviceNotRegisteredError,
    DeviceOperationError,
    DeviceSafeStateResult,
    DeviceSafeStateStatus,
    DeviceSnapshot,
    DeviceState,
    DeviceStopResult,
    DeviceStopStatus,
    ResourceBusyError,
    StopMode,
)
from .runtime.resources import ResourceArbiter, ResourceLease
from .runtime.runtime import DeviceRegistration, DeviceRuntime
from .cameras import resolve_camera_provider

__all__ = [
    "ArmId",
    "ArmMotion",
    "ArmState",
    "ArmStateReader",
    "ArmTelemetry",
    "ArmTelemetryReader",
    "BodyAxis",
    "BalanceReader",
    "BalanceReading",
    "CameraSource",
    "CartesianPose",
    "DepthCameraFrame",
    "DepthCameraSource",
    "DeviceCapability",
    "DeviceContractError",
    "DeviceErrorCategory",
    "DeviceInitializationError",
    "DeviceNotRegisteredError",
    "DeviceOperationError",
    "DeviceRegistration",
    "DeviceRuntime",
    "DeviceSafeStateResult",
    "DeviceSafeStateStatus",
    "DeviceSnapshot",
    "DeviceState",
    "DeviceStopResult",
    "DeviceStopStatus",
    "DigitalOutputs",
    "ExpressionDisplay",
    "GripperControl",
    "GrippingRobotSystem",
    "GripperTelemetry",
    "JointVector",
    "MobileBase",
    "MotionMode",
    "MotionOptions",
    "NeckMotion",
    "Pipette",
    "PowderDispenser",
    "ResourceArbiter",
    "ResourceBusyError",
    "ResourceLease",
    "resolve_camera_provider",
    "RobotOperationError",
    "RobotSystem",
    "RobotTeleoperation",
    "SelectableCameraSource",
    "StopMode",
    "StoppableDevice",
    "ToolChanger",
    "ToolRackControl",
    "TrajectoryControl",
    "TrajectorySaveResult",
]
