from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from .arm_models import (
    ArmId,
    ArmState,
    ArmTelemetry,
    CartesianPose,
    JointVector,
    MotionMode,
    MotionOptions,
    TrajectorySaveResult,
)
from .camera_models import DepthCameraFrame
from .models import StopMode


@runtime_checkable
class CloseableDevice(Protocol):
    def close(self) -> None: ...


@runtime_checkable
class StoppableDevice(Protocol):
    @property
    def supported_stop_modes(self) -> frozenset[StopMode]: ...

    def stop(self, mode: StopMode) -> None: ...


@runtime_checkable
class ArmMotion(Protocol):
    def move_to_pose(
        self,
        arm: ArmId,
        pose: CartesianPose,
        mode: MotionMode,
        options: MotionOptions | None = None,
    ) -> None: ...


@runtime_checkable
class ArmStateReader(Protocol):
    def read_arm_state(self, arm: ArmId) -> ArmState: ...
    def try_read_arm_state(self, arm: ArmId) -> ArmState | None: ...


@runtime_checkable
class ArmTelemetryReader(Protocol):
    def read_arm_telemetry(self, arm: ArmId) -> ArmTelemetry: ...
    def try_read_arm_telemetry(self, arm: ArmId) -> ArmTelemetry | None: ...


@runtime_checkable
class GripperControl(Protocol):
    def open_gripper(self, arm: ArmId) -> None: ...
    def close_gripper(self, arm: ArmId) -> None: ...
    def move_gripper(self, arm: ArmId, position: int) -> None: ...


@runtime_checkable
class RobotTeleoperation(Protocol):
    def follow_joints(
        self,
        arm: ArmId,
        joints: JointVector,
        *,
        follow: bool,
        trajectory_mode: int,
    ) -> None: ...

    def initialize_teleoperation(
        self,
        arm: ArmId,
        joints: JointVector,
        *,
        velocity: int = 10,
        radius: int = 0,
        connect: int = 0,
        block: int = 1,
    ) -> None: ...


@runtime_checkable
class TrajectoryControl(Protocol):
    def start_drag_teaching(self, arm: ArmId) -> None: ...
    def stop_drag_teaching(self, arm: ArmId) -> None: ...
    def save_trajectory(
        self,
        arm: ArmId,
        path: str | Path,
    ) -> TrajectorySaveResult: ...
    def send_trajectory(self, arm: ArmId, path: str | Path) -> None: ...
    def is_trajectory_complete(self, arm: ArmId) -> bool: ...


@runtime_checkable
class ToolRackControl(Protocol):
    def change_tool(
        self,
        slot: int,
        *,
        attach: bool,
        eject_tool: Callable[[], bool] | None = None,
    ) -> None: ...


@runtime_checkable
class RobotSystem(
    ArmMotion,
    ArmStateReader,
    GripperControl,
    CloseableDevice,
    Protocol,
):
    """Core robot capabilities that every vendor adapter must implement."""


@runtime_checkable
class BodyAxis(Protocol):
    def move_to(self, position: int) -> Any: ...
    def is_reached(self) -> bool | None: ...
    def emergency_stop(self) -> Any: ...
    def close(self) -> None: ...


@runtime_checkable
class MobileBase(Protocol):
    def move_to_position(self, location_id: int, coordinate_id: int) -> bool: ...
    def move_slowly(self, x: float, y: float, angle: float) -> bool: ...
    def close(self) -> None: ...


@runtime_checkable
class NeckMotion(Protocol):
    def move_horizontal(self, pwm: int, time_ms: int | None = None) -> Any: ...
    def move_vertical(self, pwm: int, time_ms: int | None = None) -> Any: ...
    def move_both(
        self,
        horizontal_pwm: int,
        vertical_pwm: int,
        time_ms: int | None = None,
    ) -> Any: ...
    def reset(self, time_ms: int | None = None) -> Any: ...
    def close(self) -> None: ...


@runtime_checkable
class DigitalOutputs(Protocol):
    def set_channel(self, channel: int, enabled: bool) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class ToolChanger(Protocol):
    def set_locked(self, locked: bool) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class Pipette(Protocol):
    def initialize(self) -> bool: ...
    def set_absorb_speed(self, speed_ul_s: int) -> bool: ...
    def set_dispense_speed(self, speed_ul_s: int) -> bool: ...
    def absorb(self, volume_ul: int) -> bool: ...
    def dispense(self, volume_ul: int) -> bool: ...
    def dispense_all(self) -> bool: ...
    def eject_tip(self) -> bool: ...
    def close(self) -> None: ...


@runtime_checkable
class PowderDispenser(Protocol):
    def enable_all(self) -> None: ...
    def gripper_move_to(self, percent: int) -> None: ...
    def gripper_grip(self) -> None: ...
    def gripper_release(self) -> None: ...
    def lift_up(self, steps: int) -> None: ...
    def lift_down(self, steps: int) -> None: ...
    def lift_stop(self) -> None: ...
    def lift_to_dispense(self, position: int) -> None: ...
    def lift_to_safe(self, position: int) -> None: ...
    def rotation_cw(self, steps: int) -> None: ...
    def rotation_ccw(self, steps: int) -> None: ...
    def rotation_stop(self) -> None: ...
    def rotation_move_relative(self, delta_steps: int) -> None: ...
    def rotation_to_home(self, position: int) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class CameraSource(Protocol):
    @property
    def camera_count(self) -> int: ...
    @property
    def is_running(self) -> bool: ...
    def start(self) -> dict[str, Any]: ...
    def stop(self) -> None: ...
    def get_cameras_info(self) -> list[dict[str, Any]]: ...
    def get_latest_jpegs(self) -> list[tuple[str, str, bytes]]: ...


@runtime_checkable
class DepthCameraSource(CameraSource, Protocol):
    def get_latest_raw_frames(self, camera_name: str | None = None) -> Any: ...
    def get_latest_depth_frame(
        self,
        camera_name: str | None = None,
    ) -> DepthCameraFrame | None: ...


@runtime_checkable
class ExpressionDisplay(Protocol):
    def switch(self, expression: str | int) -> Any: ...
    def close(self) -> None: ...
